.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test1.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-1.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-2.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-3.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-4.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-5.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-6.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-7.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-8.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-9.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2-a.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test2.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test41.mls
.\Debug\mlc.exe ..\..\..\public-ro\mlc\du3\tests\du3-test44.mls
